repos:
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.10

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml